### ISSUE TITLE
req: additional dark themes.

### ISSUE THREAD

**Issue by raulvasquez** [maartenpaauw/home-assistant-community-themes#4]
https://github.com/awolkers/home-assistant-themes

Is it possible to add the themes from the above repo? A few more dark theme variants.

**Comment by maartenpaauw** [comment]
Hi!

Thanks for creating an issue. I've took a look at the themes and I like them but I think I won't add them to this repository because you are able to install that themes the same way like the themes in this repository.

```
cd themes/
git clone https://github.com/awolkers/home-assistant-themes.git
```

or

```
cd themes/
git submodule add https://github.com/awolkers/home-assistant-themes.git
```

I hope this helped you enough!
