### ISSUE TITLE
add to HACS

### ISSUE THREAD

**Issue by ljmerza** [maartenpaauw/home-assistant-community-themes#5]
please add these themes to HACS
https://github.com/custom-components/hacs

**Comment by maartenpaauw** [comment]
But this is for custom components and not for themes right?

**Comment by ljmerza** [comment]
There's a section for themes https://github.com/custom-components/hacs/blob/data/repositories/theme

**Comment by maartenpaauw** [comment]
Hmmm. I found the docs and an example repo. I think we only need to move all themes into a separated folder called "themes". 

Are you willing to test this out and if it works make a PR?

https://github.com/ludeeus/theme-hacs
https://github.com/custom-components/hacs/blob/master/docs/developer/theme.md

**Comment by ljmerza** [comment]
yeah for sure

**Comment by maartenpaauw** [comment]
I took a futher look into this issue and I found the following inside the documentation.

> There is only one theme configuration file (one directory under ROOT_OF_THE_REPO/themes/) per repository (if you have more, only the first one will be managed.)

I guess this is not possible.

**Comment by maartenpaauw** [comment]
I'm reopeing this issue for future plans. Maybe we can convert this repository towards separated repositories for each theme. So you don't have to install all of the themes.

I already opened up the organisation https://github.com/home-assistant-community-themes

**Comment by maartenpaauw** [comment]
Slowly starting to migrate all to @home-assistant-community-themes
